### PR TITLE
1.3 Compatibility

### PR DESCRIPTION
**Pull request by devn**
Hello joodie,

I took a bit of time last night to get clojure-refactoring working with Clojure 1.3. The clojurecheck tests are still not passing due to `(recur)` being used across trys: `(loop []... (try ...yadda yadda... (recur...)))`

I also did some general namespace cleanup where I saw extraneous `use` or `require`.

If you have any questions let me know. Again, the tests aren't passing so there is a bit more work to be done, but I tested it after switching from `clojure.contrib.pprint` to `clojure.pprint`, and everything looks to be in working order.

Cheers,
Devin Walters (devn)

### CODE REVIEW

**Comment by joodie** [comment]
Looks interesting. However, quite a lot still needs to be done; aside from the (probably minimal) changes needed for clojurecheck, this patch also still relies on a lot of clojure.contrib that isn't compatible with clojure 1.3.

I'll start a clojure-1.3 branch from this one and see if this is fixable in a reasonable amount of time.

**Comment by joodie** [comment]
I did a bit of quick work to remove most of the difficult dependencies (some version of clojure.contrib.mock is still in). Some tests are still failing, though. 

Take a look at my [clojure-1.3 branch](https://github.com/joodie/clojure-refactoring/tree/clojure-1.3) (based on this fork) if you're interested.

**Comment by devn** [comment]
Yeah I realized today the dependencies on seq utils and so on were being pulled from the Lein plugin I installed. It does actually work though if you include contrib in the project.

Sent via mobile

**Comment by joodie** [comment]
I really don't want to have all of clojure.contrib in the dependencies, though; much of the stuff in there will break on clojure 1.3.

**Comment by devn** [comment]
My apologies for the false start on the refactoring for 1.3, but I wanted to show someone some quick examples of thread-first and thread-last for their existing code and made a mad dash to get it working. I 100% agree we should get rid of the contrib dependencies. I found that some of those dependencies are not even used in the namespaces that require them, so that might be worth a look as you're going through. 

In general, is there anything specific I can tackle on this project to get things back to "readily hackable"?

Cheers, 

## 

Devin Walters

**Comment by joodie** [comment]
No worries. I'll take any help I can get on this :)

There seem to be two general categories of bugs in the clojure-1.3 branch right now. If you're interested, see  https://github.com/joodie/clojure-refactoring/issues/2 and we can move this discussion over there.

**Comment by devn** [comment]
Sounds good. Feel free to close this.

Sent via mobile

**Pull request closed without merging**
